server:
  port: 8096
  undertow:
    threads:
      io: 8 #IO线程数, 它主要执行非阻塞的任务，它们会负责多个连接，默认设置每个CPU核心一个线程，不可设置过大，否则启动项目会报错：打开文件数过多
      worker: 32
spring:
  application:
    name: snowball-user
#multi-table-query:
#  enabeld: true
common:
  application: user # EnumApplication
  platform: snowball
  data:
    enabled: true