server:
  port: 8095
spring:
  application:
    name: snowball-agent
#multi-table-query:
#  enabeld: true
common:
  application: agent # EnumApplication
  platform: snowball
  data:
    enabled: true
