enums:
  enumClassReplaceMap:
    EnumDict: com.pro.snowball.api.enums.EnumAuthDictSnowball
    EnumTradeType: com.pro.snowball.api.enums.EnumTradeTypeSnowball
common:
  entityClassReplaceMap:
    User: com.pro.snowball.api.model.db.UserSnowball
    UserMoney: com.pro.snowball.api.model.db.UserMoneySnowball
    UserLevelConfig: com.pro.snowball.api.model.db.UserLevelConfigSnowball
    UserAmountTotal: com.pro.snowball.api.model.db.UserAmountTotalSnowball
