spring:
  datasource:
    url: jdbc:mysql://localhost:3306/snowball3?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: developer
logging:
  level:
    com.pro.snowball.common.dao: DEBUG
